language: node_js
sudo: false

git:
  depth: 10

node_js:
  - 0.8
  - 0.10
  - 0.12
  - 4
  - 6
  - 8
  - 10

install:
  - nvm --version
  - node --version
  - npm --version
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.8" ] ; then nvm install --latest-npm 0.8 ; fi'
  - npm install
  - node --version
  - npm --version

script:
  - npm test
