language: node_js
sudo: false

git:
  depth: 10

node_js:
  - 6
  - 8
  - 10

install:
  - nvm --version
  - node --version
  - npm --version
  - npm install

script:
  - npm test
  # TODO MOVE eslint into npm test once we drop Node.js pre-6.0
  - 'if [ "${TRAVIS_NODE_VERSION}" = "6" ] ; then npm run eslint ; fi'
  - 'if [ "${TRAVIS_NODE_VERSION}" = "8" ] ; then npm run eslint ; fi'
  - 'if [ "${TRAVIS_NODE_VERSION}" = "10" ] ; then npm run eslint ; fi'
